name = "DanceDocker"
uuid = "0b4dc4cd-9a07-490e-bcea-830d79495a0b"
authors = ["Chris \"Yoh\" Meyers <48554065+yoh-meyers@users.noreply.github.com>"]
version = "0.0.1"

[compat]
julia = "1.1"

[extras]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["HTTP", "Pkg", "SafeTestsets", "Test"]
